---
title: qta — our own features
execute:
  enabled: true
---

Hand-rolled feature primitives, one file per feature under `qrt/feat/qta/`.
These code cells are **executed live** by Quarto every time the docs are built.

## Sample data

We use qrt's bundled AAPL sample dataset — loaded offline via `q.data.datasets.load`,
no network dependency (see the [Data](../data/index.qmd) tutorial for more on
`q.data`):

In [1]:
import pandas as pd

import qrt as q

aapl = q.data.datasets.load("aapl")
aapl.tail()

                  open        high         low       close    volume
datetime
2026-07-13  317.019989  323.450012  315.779999  317.309998  43257800
2026-07-14  313.760010  316.190002  311.910004  314.859985  36336800
2026-07-15  317.619995  328.730011  317.320007  327.500000  60957600
2026-07-16  328.010010  334.679993  326.790009  333.260010  62970600
2026-07-17  331.980011  334.989990  329.000000  333.739990  63365300

Hand-rolled primitives, one file per feature under `qrt/feat/qta/`:

In [2]:
sma_20 = q.feat.qta.sma(aapl["close"], 20)
sma_100 = q.feat.qta.sma(aapl["close"], 100)

price_features = pd.DataFrame({"close": aapl["close"], "sma_20": sma_20, "sma_100": sma_100})
price_features.tail()

                 close      sma_20     sma_100
datetime
2026-07-13  317.309998  299.187001  279.561089
2026-07-14  314.859985  300.373500  280.068622
2026-07-15  327.500000  301.927499  280.740221
2026-07-16  333.260010  303.628500  281.429456
2026-07-17  333.739990  305.517999  282.107506

In [3]:
q.feat.qta.lags(aapl["close"], [1, 5, 21]).tail()

            close_lag1  close_lag5  close_lag21
datetime
2026-07-13  315.320007  312.660004   291.579987
2026-07-14  317.309998  310.660004   295.630005
2026-07-15  314.859985  313.390015   291.130005
2026-07-16  327.500000  316.220001   296.420013
2026-07-17  333.260010  315.320007   299.239990

To add a feature, create `qrt/feat/qta/<feature>.py` with one public function and
re-export it in `qrt/feat/qta/__init__.py` (one import line + one `__all__` entry).

## Visualizing features

`q.plot.col` renders any feature DataFrame as an interactive Plotly chart with
hover, zoom, and range-selector buttons — handy for eyeballing an indicator
against price before using it in a model:

In [4]:
fig = q.plot.col(
    price_features,
    title="AAPL close price with SMA overlays",
    ylabel="Price",
    height=450,
)
fig.show()